jwt:
  secret: techgeeknext
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-02.cleardb.com:3306/heroku_e8954d2947d0761?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bd58b571b30f19
    password: ENC(6p7iMeVjzONuqAoBNtfDavPXwcYo0NKi)
    platform: mysql
    initialization-mode: always
  jpa:
    properties:
      hibernate: dialect:org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
jasypt:
  encryptor:
    password: secretpass
server:
  port: 8080

